version: '3.1'
services:
  app:
    container_name: contenedor_php
    image: ttania/bookmedik:v1
    restart: always
    networks:
      - bookmedik-network
    environment:
      DB_HOST: servidor_mysql
      DB_USER: admin
      DB_PASS: admin
      DB_NAME: usuarios
    ports:
      - 8080:80
    depends_on:
      - db
  db:
    container_name: servidor_mysql
    image: mariadb
    restart: always
    networks:
      - bookmedik-network
    environment:
      MYSQL_DATABASE: usuarios
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: asdasd
    volumes:
      - mariadb_data:/var/lib/mysql
volumes:
    mariadb_data:

networks:
    bookmedik-network:
